// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuRnRSBaxEGqFBfBu2Gmuu7Q6EgMomdq8',
    appId: '1:428329879965:android:4b34c16f14a2808c3d8774',
    messagingSenderId: '428329879965',
    projectId: 'fir-4dbab',
    storageBucket: 'fir-4dbab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvPGopYFOu-sk1NXE0WnkiqdkbFl_1UCE',
    appId: '1:428329879965:ios:df4cb5d0ee22223f3d8774',
    messagingSenderId: '428329879965',
    projectId: 'fir-4dbab',
    storageBucket: 'fir-4dbab.appspot.com',
    androidClientId: '428329879965-28k31pfakl2e7d2qercimc2toab7im8a.apps.googleusercontent.com',
    iosClientId: '428329879965-chd1n9ub2jc31l96jgkj9qskq8h7n6r4.apps.googleusercontent.com',
    iosBundleId: 'com.example.seen',
  );

}